#!/usr/bin/env bash

######## Static ###############

__defaultExtension=txt
__dbg=0
__supportedExtensions=( txt rtf doc docx )
__tempDir="wc_temp"

######### Input Params #########

__ext=${1-${__defaultExtension}}

######### Functions ############

convertTempDirToTxtFormat() {
    dbg "converting files in ${__tempDir} to txt..."

    if [[ "$__ext" -eq "txt" ]]
        then return
    fi

    textutil -convert txt ${__tempDir}/*
}

countAllTxtFilesInTempDir() {
    dbg "word counting all txt in ${__tempDir}..."
    cat ${__tempDir}/*.txt | wc -w
}

copyFilesWithExtensionToTempDir() {
    local _ext=$1
    local _fileFormat=*.${_ext}
    dbg "copying files with extension ${_ext} to ${__tempDir} ..."

    cp ${_fileFormat} ${__tempDir}
}

dbg() {
    if [[ ${__dbg} != 1 ]]
        then return
    fi

    echo $1
}

makeTempDir() {
    dbg "making temp dir ${__tempDir}..."
    mkdir -p ${__tempDir}
}

remTempDir() {
    dbg "removing ${__tempDir}..."
    rm -r ${__tempDir}
}

######### Main #########
main() {
    makeTempDir
    copyFilesWithExtensionToTempDir ${__ext}
    convertTempDirToTxtFormat
    count=$(countAllTxtFilesInTempDir)
    remTempDir

    echo ${count}
}

main