#!/usr/bin/env bash

######## Static ###############

__defaultExtension=docx
__supportedExtensions=( "txt" "rtf" "doc" "docx" )
__tempDir="words_temp"

######### Input Params #########

__ext=${1-${__defaultExtension}}

######### Functions ############

function convertTempDirToTxtFormat() {
    if [[ "$__ext" = "txt" ]]
        then return
    fi

    textutil -convert txt ${__tempDir}/*
}

function countAllTxtFilesInTempDir() {
    cat ${__tempDir}/*.txt | wc -w
}

function copyFilesWithExtensionToTempDir() {
    local _ext=$1
    cp *.${_ext} ${__tempDir}
}

function makeTempDir() {
    mkdir -p ${__tempDir}
}

function remTempDir() {
    rm -r ${__tempDir}
}

######### Param Validation #########
function validateExtension() {
    for _ext in ${__supportedExtensions[*]}
    do
        if [[ ${_ext} = ${__ext} ]]
            then return
        fi
    done

    return 1
}

function validateParams() {
    validateExtension
    if [[ $? != 0 ]]
        then
            printf "The extension ${__ext} is not supported."
            exit 1
    fi
}

######### Main #########

main() {
    validateParams

    makeTempDir
    copyFilesWithExtensionToTempDir ${__ext}
    convertTempDirToTxtFormat
    local count=$(countAllTxtFilesInTempDir)
    remTempDir

    printf "%s\n" ${count}
}

######### Entry point #########

main